### PR TITLE
API Weekend Lab

### PR DESCRIPTION
**Pull request by cameronjacoby**

### CODE REVIEW

**Comment by cameronjacoby** [comment]
No longer WIP -- please review.

Let me know if anyone has any other suggestions for the docs/resources section. Right now they are mostly module notes for the related topics.

Thanks! :smile:

**Comment by ben-manning** [comment]
Everything looks good to me.  I didn't find any typos and it seems like the directions seem pretty clear for the students.

**Comment by cameronjacoby** [comment]
Thanks, @ben-manning! :+1:

**Comment by cameronjacoby** [comment]
FYI for everyone:

We're giving this to the students on Friday, not today. I think we all knew that, but just wanted to make sure it was clear.

Also, I wasn't planning on writing a solution for this, because Catchphrasely basically is the solution. Let me know if objections.

**Pull request merged**
