### PR TITLE
Solution and README for update delete

### PR DESCRIPTION
**Pull request by bgveenstra**
please review for Wednesday afternoon.

The README is the current module notes. The catchphrasely directory is the lab solution but will probably also serve as an in-class example.

Please also check that the code excerpts in README match the code from catchphrasely.

### CODE REVIEW

**Comment by bgveenstra** [comment]
We should probably change POST for update to PUT, to match what students learned [Tuesday morning](https://github.com/sf-wdi-19-20/modules/tree/master/w3_d2_1_api_crud)

Edit: hooray for learning. The most correct HTTP request type for changing only one field of data seems to be PATCH, which was mentioned Tuesday morning (though perhaps we still wouldn't do it [wholly correctly](http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/) ) .  PUT is expected to update the entire object at once, and that's not the current behavior of the phrase update.

**Comment by bgveenstra** [comment]
also possibly a good call to change app.js on the front end to script.js or whatever they've been using

**Comment by bgveenstra** [comment]
... and instead of res.send(JSON.stringify....) looks like we could use res.json that they saw the other day

**Comment by cameronjacoby** [comment]
Closing this b/c the solution is now moved to a separate repo, called w3_catchphrasely

**Pull request closed without merging**
